  GNU nano 4.8                                              docker-compose.yaml
version: '3.8'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: lisawhitealt/yamdb
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./static:/code/static
      - ./media:/code/media
    depends_on:
      - web

volumes:
  postgres_data: